### ISSUE TITLE
Conda-package-handling release 1.9

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-package-handling#120]
### Summary

Placeholder for `conda-package-handling 1.9` release.

### Tasks

- [x] Complete outstanding PRs
    - [x] #115
- [x] #127 
    - See release process https://github.com/conda/infra/issues/541
- [x] [Publish Release](https://github.com/conda/conda-package-handling/releases/tag/1.9.0)
- [x] Create/update `1.x` branch
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-package-handling-feedstock/pull/6
    - [x] https://github.com/conda-forge/conda-package-handling-feedstock/pull/64
- [x] Handoff to packaging team
- [x] Announce release
    - [x] Slack
    - [x] Twitter

**Comment by dholth** [comment]
cph extract was broken, would be good to fix that
