### ISSUE TITLE
Release conda-package-handling 2.0

### ISSUE THREAD

**Issue by dholth** [conda/conda-package-handling#133]
### Summary

Placeholder for `conda-package-handling 2.0` release.

2.0 is a major release because it removes libarchive, and adds a `conda-package-streaming` and `zstandard` dependency. This changes the way `conda` and `conda-build` work, but in a compatible way if we've done the work correctly.

### Tasks

- [x] Complete outstanding PR
- [ ] Publish Release
- [ ] Feedstocks
- [x] Ensure conda-package-streaming >=0.6.0 is available
- [ ] Handoff to packaging team
- [ ] Announce release
    - [ ] Slack
    - [ ] Twitter

**Comment by dholth** [comment]
conda-forge feedstock https://github.com/conda-forge/conda-package-handling-feedstock/pull/68
