### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by dholth** [conda/conda-package-handling#201]
### Summary

Placeholder for `conda-package-handling 2.1.0` release.

(copied/pasted from more complicated conda release process; some of these steps may not be necessary).

- [] Do #189 as part of this release

| Pilot | <pilot> |
|---|---|
| Co-pilot | <copilot> |

### Tasks

[milestone]: {{ repo.url }}/milestone/<milestone>
[process]: {{ repo.url }}/blob/main/RELEASE.md
[releases]: {{ repo.url }}/releases
[main]: https://github.com/AnacondaRecipes/{{ repo.name }}-feedstock
[conda-forge]: https://github.com/conda-forge/{{ repo.name }}-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-{{ repo.name }}/
[announcement]: https://github.com/conda/communications

#### The week before release week

- [ ] Create release branch (named `YY.M.x`)
- [ ] Ensure release candidates are being successfully built (see `conda-canary/label/YY.M.x`)
- [ ] [Complete outstanding PRs][milestone]
- [ ] Test release candidates
    

#### Release week

- [ ] Create release PR (see [release process][process])
- [ ] [Publish release][releases]
- [ ] Activate the `YY.M.x` branch on [ReadTheDocs][ReadTheDocs]
- [ ] Feedstocks
    - [ ] Bump version & update dependencies/tests in [Anaconda, Inc.'s feedstock][main]
    - [ ] Bump version & update dependencies/tests in [conda-forge feedstock][conda-forge]
    
- [ ] Hand off to the Anaconda packaging team
- [ ] Announce release
    - [ ] Create release [announcement draft][announcement]
    - [ ] Discourse
    - [ ] Twitter
    - [ ] Matrix
