### ISSUE TITLE
Release 2.2.0

### ISSUE THREAD

**Issue by dholth** [conda/conda-package-handling#220]
### Summary

Placeholder for `conda-package-handling 2.2.0` release.

| Pilot | dholth |

### Tasks

[milestone]: https://github.com/conda/conda-package-handling/milestone/<milestone>
[process]: https://github.com/conda/conda-package-handling/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-package-handling/releases
[main]: https://github.com/AnacondaRecipes/conda-package-handling-feedstock
[conda-forge]: https://github.com/conda-forge/conda-package-handling-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda-package-handling/

#### The week before release week

- [x] Create release branch (named `YY.M.x`)
- [ ] Ensure release candidates are being successfully built (see `conda-canary/label/YY.M.x`)
- [x] [Complete outstanding PRs][milestone]
- [ ] Test release candidates
    

#### Release week

- [x] Create release PR (see [release process][process])
- [x] [Publish release][releases]
- [ ] Activate the `YY.M.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] Bump version & update dependencies/tests in [Anaconda, Inc.'s feedstock][main]
    - [x] Bump version & update dependencies/tests in [conda-forge feedstock][conda-forge]
    
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [ ] conda.org (link to pull request)
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

### Linked Issues & PRs

- [x] #216

**Comment by beckermr** [comment]
The bot found that v2.2.0 now imports zstandard but the dependencies have not been updated: https://github.com/conda-forge/conda-package-handling-feedstock/pull/75

**Comment by dholth** [comment]
@beckermr It is designed to work without zstandard "in case of emergency" https://github.com/conda/conda-package-handling/blob/main/src/conda_package_handling/api.py#L28-L29

It should depend on conda-package-streaming >=0.9.0 to pull in a conda-package-streaming umask fix.

conda-package-streaming depends on zstandard.

**Comment by dholth** [comment]
It would be appropriate to depend on zstandard directly.

We test the alternate case here since if you don't have zstandard, it would be really nice to be able to install it. https://github.com/conda/conda-package-handling/blob/main/tests/test_degraded.py
