### ISSUE TITLE
Release 2.3.0?

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-package-handling#240]
There are a couple nice changes in the [`news/`](https://github.com/conda/conda-package-handling/tree/main/news) folder. What about merging https://github.com/conda/conda-package-handling/pull/231 and cutting a new release?

### Summary

Placeholder for `conda-package-handling YY.M.x` release.

| Pilot |  dholth |
|---|---|
| Co-pilot | jezdez |

### Tasks

[milestone]: https://github.com/conda/conda-package-handling/milestone/<milestone>
[process]: https://github.com/conda/conda-package-handling/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-package-handling/releases
[main]: https://github.com/AnacondaRecipes/conda-package-handling-feedstock
[conda-forge]: https://github.com/conda-forge/conda-package-handling-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda-package-handling/

<details open>  
<summary><h4>The week before release week</h4></summary>

- [x] Create release branch (named `release-2.3.0`)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-package-handling-YY.M.x`)
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates
    

</details>

<details open>  
<summary><h4>Release week</h4></summary>

- [x] Create release PR (see [release process][process])
- [x] [Publish release][releases]
- [x] Merge `YY.M.x` back into `main`
- [x] Activate the `YY.M.x` branch on [ReadTheDocs][ReadTheDocs]
- [ ] Feedstocks
    - [ ] Bump version & update dependencies/tests in [Anaconda, Inc.'s feedstock][main]
      - [ ] https://github.com/AnacondaRecipes/conda-package-handling-feedstock/pull/13
    - [x] Bump version & update dependencies/tests in [conda-forge feedstock][conda-forge]
      - [ ] https://github.com/conda-forge/conda-package-handling-feedstock/pull/76
    
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [ ] conda.org (link to pull request)
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

**Comment by jaimergp** [comment]
@conda/conda-core thoughts?

**Comment by travishathaway** [comment]
I'd be happy to help with this.

**Comment by jaimergp** [comment]
Thanks @travishathaway. Looks like @dholth has a PR at #243 which is simple enough to make it to the merge queue. I guess we can start the release process after that. I'm not sure which process that is though, since I don't see items in the `news/` directory :/

**Comment by dholth** [comment]
#243 also includes code coverage improvements for cph list

**Comment by jaimergp** [comment]
Ping @dholth, are we ready now? It looks like the merge queue is clear :D

**Comment by dholth** [comment]
Yes, we should do a release.

**Comment by jezdez** [comment]
Closing since 2.3.0 was released.
