### ISSUE TITLE
Release 2.4.0

### ISSUE THREAD

**Issue by dholth** [conda/conda-package-handling#268]
### Summary

Placeholder for `conda-package-handling 2.4.0` release.

| Pilot | dholth |
|---|---|
| Co-pilot | <copilot> |

### Tasks

[process]: https://github.com/conda/conda-package-handling/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-package-handling/releases
[main]: https://github.com/AnacondaRecipes/conda-package-handling-feedstock
[conda-forge]: https://github.com/conda-forge/conda-package-handling-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda-package-handling/

<details open>  
<summary><h4>The week before release week</h4></summary>

- [x] Create release branch (named `release-2.4.0`)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-package-handling-MAJOR.MINOR.x`)
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates
    

</details>

<details open>  
<summary><h4>Release week</h4></summary>

- [x] Create release PR (see [release process][process])
- [x] [Publish release][releases]
- [x] Merge `2.4.0` back into `main`
- [x] Feedstocks
    - [x] Bump version & update dependencies/tests in [Anaconda, Inc.'s feedstock][main]
    - [x] Bump version & update dependencies/tests in [conda-forge feedstock][conda-forge]
    
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [ ] conda.org (link to pull request)
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

</details>
